### ISSUE TITLE
Demo picture of carousel view in use

### ISSUE THREAD

**Issue by techscientist** [sayyam/carouselview#1]
Hi,

Nice project! I thought it would be nice if you could add a demo picture in the README.md file of the carouselview in use, so that we can see how it looks like and functions.

Thanks.

**Comment by ThimoKl** [comment]
Here's a preview GIF:
http://i.imgur.com/ALPu8ns.gif

**Comment by sayyam** [comment]
Thanks a lot @ThimoKl, I have added banner and gif for that.

**Comment by techscientist** [comment]
Thanks guys
