### ISSUE TITLE
How to make round corners of the carouselview 

### ISSUE THREAD

**Issue by sumit-kmr** [sayyam/carouselview#119]
Is there any way to round the corners of the whole carouselview?

**Comment by aqeel371** [comment]
You can add `ViewListener` inside of `ImageListener` and can use custom view like this
```
var viewListener:ViewListener = object :ViewListener{
        override fun setViewForPosition(position: Int): View {
            val view = layoutInflater.inflate(R.layout.item_slider, null)
            view.ivSlider.setImageResource(sampleImages[position])
            return view
        }

    }
```
<img width="297" alt="Screenshot 2020-05-10 at 10 44 15 AM" src="https://user-images.githubusercontent.com/26341580/81491763-34231a00-92ab-11ea-87dd-349a91a3b524.png">
