### ISSUE TITLE
Keep images from filling space

### ISSUE THREAD

**Issue by rawlen** [sayyam/carouselview#15]
I'm using Picasso with fit().centerInside(), but it only scales as much as the smaller dimension, meaning the top and bottom of my images are cropped. Is there a way to get around this? I don't want it to fill the space.

My dimensional settings are the same as the example, but my images are taller than they are wide.

**Comment by sayyam** [comment]
@rawlen : You can use `CenterCrop() ` instead of `fit().centerInside()`, this method scales the image so that it fills the requested bounds of the ImageView and then crops the extra. The ImageView will be filled completely, but the entire image might not be displayed.

**Comment by rawlen** [comment]
This did not work. `centerCrop()` without `fit()` throws an exception because it was not made to work by itself. `Resize().centerCrop()` works no differently than `fit().centerCrop()`, which appears to have the same effect as `resize().centerInside()`.

Sorry for the delay - I couldn't test your suggestion until now. I tried some variations to confirm that it wasn't working. Square images cause the same problems.

**Comment by rawlen** [comment]
I figured out a fix. From looking at your code, I saw that you set the `imageView` scale type before calling `setImageForPosition()`, so I reset the scale type to `CENTER_INSIDE` instead of `CENTER_CROP` within `setImageForPosition()`.
