### ISSUE TITLE
FATAL EXCEPTION

### ISSUE THREAD

**Issue by iWooli** [sayyam/carouselview#17]
Hi,

I'm trying to set the library normally but I'm having a fatal exception thrown at this point `carouselView.setPageCount(sampleImages.length);`
 Here is the error 
`FATAL EXCEPTION: main Process: com.iwooli.xxxxxx, PID: 28670 java.lang.RuntimeException: View must set ImageListener or ViewListener.`

**Comment by sayyam** [comment]
your `carouselView` must set `ImageListener` or `ViewListener`.
Please implement `ImageListener` or `ViewListener` and set it:

carouselView.setImageListener(imageListener);

```
    ImageListener imageListener = new ImageListener() {
        @Override
        public void setImageForPosition(int position, ImageView imageView) {
            imageView.setImageResource(sampleImages[position]);
        }
    };
```

**Comment by iWooli** [comment]
Thanks for the reply. I found my way ;)

**Comment by tommyapk** [comment]
i got same error. i following this code but it still error. i use fragment for layout

**Comment by vincepunkrock** [comment]
> i got same error. i following this code but it still error. i use fragment for layout

Make sure you call setImageListener on the carouselView before you call setPageCount. I just had the same problem and it fixed it.
