### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by sohayb** [sayyam/carouselview#2]
Nice piece of code you have there :+1: 
Is there any plan to add looping (infinite scrolling) to the Carousel?

Thanks

**Comment by sayyam** [comment]
@sohayb Thanks for your appreciation. We have added your suggestion in our todo

**Comment by sohayb** [comment]
awesome! thanks

**Comment by MasterzYuri** [comment]
Also waiting for infinite scrolling feature.

**Comment by vikramdpatil** [comment]
+1

**Comment by abeemukthees** [comment]
Still waiting...

**Comment by gweiss27** [comment]
need infinite scroll.  Without it, this is useless to me.  Would like to use it.  Timeline???

**Comment by gweiss27** [comment]
Hey when are you doing this?  We all need infinite scroll.  Please advise?

**Comment by mikhailperemitko** [comment]
I'm waiting for this feature as well, it would very nice if you'll implement it!

**Comment by Elytum** [comment]
Waiting as well

**Comment by hendrowijaya96** [comment]
still in todo?

> @sohayb Thanks for your appreciation. We have added your suggestion in our todo

**Comment by ryxryx** [comment]
+1
