### ISSUE TITLE
Current position

### ISSUE THREAD

**Issue by julianfalcionelli** [sayyam/carouselview#35]
Hi! There is a way to get the current position of the selected page in the CarouselView ?

I need to change programmatically the selected page to the next o previous.

Thanks!

**Comment by PauloMartins** [comment]
Hi!
you can use the method **addOnPageChangeListener** to listen changes in the carouselView, then you update a local variable with the current position of the slide, eg:

```
private int currentSlide = 0;

carouselView.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(...) { }

            @Override
            public void onPageSelected(int position) {
                currentSlide = position;
            }

            @Override
            public void onPageScrollStateChanged(int state) {}
});
```

So, when necessary, you can get the current slide using the **currentSlide** variable.

**Comment by julianfalcionelli** [comment]
Thanks!
