### ISSUE TITLE
Proguard config file?

### ISSUE THREAD

**Issue by jbmlaird** [sayyam/carouselview#40]
I get the following exception upon launch when using ProGuard. Any ideas?

android.view.InflateException: Binary XML file line #97: Error inflating class com.synnapps.carouselview.CarouselView

**Comment by bamdad01** [comment]
put this line of code in your proguard-rules.pro file
`-keep class com.synnapps.carouselview.** { *; }`

**Comment by SaifurRahmanMohsin** [comment]
This should be mentioned in README.md

**Comment by assifgit** [comment]
I have added the above line in proguard-rules.pro file.
It is working perfectly while debug apk.
But when I generate the signed APK , The error comes again.

Thanks in Advance.
