### ISSUE TITLE
indicatorGravity:center_horizontal isn't  working as expected

### ISSUE THREAD

**Issue by aprendizfc** [sayyam/carouselview#42]
Hi guys, I want to center horizontal the indicators but when I try to do it the indicators go to the top left corner

`<com.synnapps.carouselview.CarouselView`
            `android:id="@+id/carouselView"`
            `android:layout_width="match_parent"`
            `android:layout_height="200dp"`
            `app:fillColor="#FFFFFFFF"`
            `app:pageColor="#00000000"`
            `app:radius="6dp"`
            `app:slideInterval="3000"`
            `app:strokeColor="#FF777777"`
            `app:strokeWidth="1dp"`
            `app:indicatorOrientation="horizontal"`
            `app:indicatorGravity="center_horizontal"`
            `app:pageTransformer="slide_over" />`

And this the result
[https://postimg.org/image/jglj2sg4v/](url)

Is there a way to solve it?

thanks in advance guys

**Comment by Nutomic** [comment]
Found a workaround [here](https://github.com/sayyam/carouselview/issues/8#issuecomment-200239197). You have to set gravity again after setting the item count:
```
carouselView.setPageCount(images.size());
carouselView.setIndicatorGravity(Gravity.CENTER_HORIZONTAL | Gravity.TOP);
```

@sayyam Please fix the library so this hack is not required :)
