### ISSUE TITLE
How can I get current page index?

### ISSUE THREAD

**Issue by SoftDev0420** [sayyam/carouselview#44]
I checked the code and found that CirclePageIndicator has mCurrentPage variable.
We can use it but it's private.
Can we make a public function to get it?

**Comment by SoftDev0420** [comment]
@sayyam Please let me know if it's possible.

**Comment by SoftDev0420** [comment]
Do I have to use OnPageChangeListener?

**Comment by SoftDev0420** [comment]
Best solution is to use **OnPageChangeListener** for now.

**Comment by sayyam** [comment]
Fixed in 0.0.10. Exposed getCurrentItem().
