### ISSUE TITLE
How to make carouselview clickable?

### ISSUE THREAD

**Issue by SoftDev0420** [sayyam/carouselview#45]
I'm going to move to next page, when carouselview is clicked.
How can I implement this feature?

**Comment by SoftDev0420** [comment]
Here is the solution.

CarouselViewPager pager = (CarouselViewPager) view.findViewById(R.id.containerViewPager);
            final GestureDetector tapGestureDetector = new GestureDetector(context, new TapGestureListener());
            pager.setOnTouchListener(new View.OnTouchListener() {
                public boolean onTouch(View v, MotionEvent event) {
                    tapGestureDetector.onTouchEvent(event);
                    return false;
                }
            });


class TapGestureListener extends GestureDetector.SimpleOnGestureListener{
            @Override
            public boolean onSingleTapConfirmed(MotionEvent e) {
                // Here you can do anything you want.
                return false;
            }
        }

**Comment by leonardo2204** [comment]
I've dropped a PR with this feature, hope the author reviews and accept it !
