### ISSUE TITLE
Scale Image 

### ISSUE THREAD

**Issue by CoderJava** [sayyam/carouselview#49]
How can I scale image in CarouselView?

**Comment by leonardo2204** [comment]
As of [this line](https://github.com/sayyam/carouselview/blob/master/carouselview/src/main/java/com/synnapps/carouselview/CarouselView.java#L307) you actually can't, the lib takes care of it automatically.
I think it would be great to users be able to set it up as a parameter. 
I'll see how much work that would take and if possible I'll drop a PR !
