### ISSUE TITLE
Stop Auto Scroll

### ISSUE THREAD

**Issue by tonespy** [sayyam/carouselview#5]
Is there a way to stop autoscroll?

**Comment by sayyam** [comment]
@tonespy Do you want to stop it somewhere midway or disable it altogether ?

**Comment by tonespy** [comment]
I mean Disable it all together. I only want the user to swipe to change the page

**Comment by sayyam** [comment]
It will be available in next version which I will be uploading in few hours from now.

**Comment by tonespy** [comment]
Okay. Thanks. Please keep me updated too

**Comment by sayyam** [comment]
@tonespy Updated and deployed v0.0.4.  
Please have a look at README for further details.
