### ISSUE TITLE
Question: There is a way to hide the indicators?

### ISSUE THREAD

**Issue by juanpaternina** [sayyam/carouselview#58]
Hello i like the way to implement this library but i can find the way to hide indicators. 

Can you help me?

Regards.

**Comment by powerhcm8** [comment]
Set all the color to transparent.

app:fillColor="#00000000"
app:pageColor="#00000000"
app:strokeColor="#00000000"

**Comment by sayyam** [comment]
Fixed. Added `indicatorVisibility` attribute. @juanpaternina

**Comment by shubhamkhuva** [comment]
Cannot access 'indicatorVisibility': it is private in 'CarouselView'
