### ISSUE TITLE
Any way to add images via Glide/Picasso?

### ISSUE THREAD

**Issue by skmlcd** [sayyam/carouselview#6]
Is there any way to add images after activity is created via something like Glide or Picasso?

**Comment by sayyam** [comment]
@skmlcd I am working on Picasso integration at the moment. So currently it is not possible the way we are used to with Picasso/Glide. However if you have the bitmap, you can set it in `setImageForPosition()` method in `ImageListener` callback.

I'll update this ticket as soon as I am done.

**Comment by sayyam** [comment]
Meanwhile you can try this, but it might cause some network overhead.

```
    ImageListener imageListener = new ImageListener() {
        @Override
        public void setImageForPosition(int position, ImageView imageView) {

            Picasso.with(getApplicationContext()).load("https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=350&h=150").fit().centerCrop().into(imageView);

        }
    };
```

**Comment by skmlcd** [comment]
Works nicely!

**Comment by wongmingrui** [comment]
Just insert a linearlayout inbetween will do.

ScrollView
     LinearLayout
          CarousellView
