### ISSUE TITLE
wrap_content is not working as a height

### ISSUE THREAD

**Issue by slikasgiedrius** [sayyam/carouselview#74]
Any suggestions? I do not want to hardcode the height.

**Comment by slikasgiedrius** [comment]
Srsly? No response at all?

**Comment by piedcipher** [comment]
Same issue! :(

**Comment by piedcipher** [comment]
Hey @slikasgiedrius, I tried tweaking few things & it worked, not exactly like `wrap_content` but it works for me. :)

So, In `activity_main.xml` (layout file)
```
android:layout_height="0dp"
android:layout_weight="1"
```

.. & in `MainActivity.java` file, add `udacity_ImageView.setAdjustViewBounds(true);` in `setImageForPosition` method.

```
ImageListener imageListener = new ImageListener() {
        @Override
        public void setImageForPosition(int thisImage, ImageView imageView) {
            imageView.setImageResource(images[thisImage]);
            imageView.setAdjustViewBounds(true); // here
        }
};
```

**Comment by yusufaw** [comment]
I have just tried solution from @piedcipher but still not working, now I change to this library
https://github.com/saeedsh92/Banner-Slider. It supports `wrap_content`.

**Comment by giedriusslikas** [comment]
@yusufaw @piedcipher Thanks for help, it looks like it's time to look for another library

**Comment by itvignes09** [comment]
>             imageView.setAdjustViewBounds(true); // here

Sad, your solution is not working for me

**Comment by itvignes09** [comment]
> Hey @slikasgiedrius, I tried tweaking few things & it worked, not exactly like `wrap_content` but it works for me. :)
> 
> So, In `activity_main.xml` (layout file)
> 
> ```
> <com.synnapps.carouselview.CarouselView
>        .
>        .
>        android:layout_height="0dp"
>        android:layout_weight="1" />
> ```
> 
> .. & in `MainActivity.java` file, add `udacity_ImageView.setAdjustViewBounds(true);` in `setImageForPosition` method.
> 
> ```
> ImageListener imageListener = new ImageListener() {
>         @Override
>         public void setImageForPosition(int thisImage, ImageView imageView) {
>             imageView.setImageResource(images[thisImage]);
>             imageView.setAdjustViewBounds(true); // here
>         }
> };
> ```

@piedcipher your solution is not working for me, Sad
