### ISSUE TITLE
app:indicatorGravity XML attribute possible bug

### ISSUE THREAD

**Issue by skmlcd** [sayyam/carouselview#8]
If I set XML attribute ```app:indicatorGravity="center_horizontal"``` ```app:indicatorGravity="top|center_horizontal"``` then indicator disappears.

I'm using version 0.0.7

I know this library is quite new, so I'm sorry if I'm reporting bugs that you already know about. Just in case. :)

**Comment by sayyam** [comment]
Give me your whole `com.synnapps.carouselview.CarouselView` tag.

**Comment by skmlcd** [comment]
```xml
<com.synnapps.carouselview.CarouselView
        android:id="@+id/carouselView"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        android:background="#444"
        app:autoPlay="false"
        app:fillColor="#FFFFFFFF"
        app:pageColor="#00000000"
        app:indicatorGravity="top|center_horizontal"
        app:radius="6dp"
        app:strokeColor="#FF777777"
        app:strokeWidth="1dp" />
```

**Comment by sayyam** [comment]
@skmlcd This is working fine with `center_horizontal` in sample. Please verify.

**Comment by skmlcd** [comment]
I have copy&pasted the sample (also from README.md too) and the indicator is not shown at all unless I add ```app:indicatorGravity="top"```

It doesn't work if the value is ```center_horizontal``` nor ```top|center_horizontal```

I have downloaded this repo and the sample works. Any tips how to debug this problem?

**Comment by skmlcd** [comment]
It's not Gradle. I have changed the repo sample to use the library from Gradle and example still works. I will look at the code from my project and this sample project to see what are the differences.

In my project I use lots of different libraries, is it possible that there are some conflicts or something similar to that?

**Comment by skmlcd** [comment]
I have found the problem.

1 . in onCreate method in my activity I setup my CarouselView object and empty ArrayList (because I don't have my images yet and I don't know many are there).

```java
allImages= new ArrayList<>();
carouselView = (CarouselView) findViewById(R.id.carouselView);
carouselView.setPageCount(allImages.size());
carouselView.setImageListener(imageListener);
```

This is my Glide code:
```java
ImageListener imageListener = new ImageListener() {
    @Override
    public void setImageForPosition(int position, ImageView imageView) {
        Glide.with(getApplicationContext())
	            .load(allImages.get(position))
	            .centerCrop()
	            .placeholder(R.mipmap.image_placeholder)
	            .into(imageView);
    }
};
```
Since the ArrayList is size 0 at the start there is no problem.

2 . via Retrofit in JSON I get the URLs of my images. Then I add those images to my ArrayList.
```java
public void updateImages(Images images) {
    if (images.getImages().size() != 0) {
        for (int i = 0; i < images.getImages().size(); i++) {
            allImages.add(images.getImages());
        }
    }

    carouselView.setPageCount(allImages.size());
}
```

If I add ```app:indicatorGravity="top"``` to my XML then indicator is shown normally (only aligned to the left). If I change to ```app:indicatorGravity="top|center_horizontal"``` then the indicator dots disappear.

If I preset the image URLs in the beginning and set the correct size of carouselView in onCreate, then ```center_horizontal``` works.

Since I don't know my URLs when activity is created, what would be the best solution here?

**Comment by sayyam** [comment]
Try setting gravity after setting pageCount.
```
carouselView.setPageCount(allImages.size());
carouselView.setIndicatorGravity(Gravity.CENTER_HORIZONTAL|Gravity.TOP);
```

**Comment by skmlcd** [comment]
Thanks, that fixed the problem.

**Comment by rivancic** [comment]
@sayyam You could put setIndicatorGravity() inside setPageCount() method so then the position would be fixed for this case. 
Then there will be no need for the user with that problem to search for that issue that is already closed and adding additional line after you set pageCount from 0 to something.

**Comment by miraclecra** [comment]
app:strokeColor="#00000000"
or 
app:strokeWidth="0dp"
is not working.
