### ISSUE TITLE
How to refresh the carousel ?

### ISSUE THREAD

**Issue by babeuloula** [sayyam/carouselview#80]
Hi, 

I load the datas from a databases and the carousel does not refresh the content. I must click again on the button to have the content.

So, how I can refresh or clear the carousel ?

Thanks.

**Comment by ravelinx22** [comment]
I'm having the same issue

**Comment by babeuloula** [comment]
To fix this I start my fonction twice. But it's not the good way. I hope have a better solution in the futur

**Comment by MateusLB** [comment]
I'm having the same issue

**Comment by mmagician** [comment]
Seems that setPageCount(yourCount) does the job. If you look at source code, you'll see it is the only method that calls setData()
